### ISSUE TITLE
Random "KeyError: 'user_id'".. possibly due to weird timing?

### ISSUE THREAD

**Issue by dzshn** [dzshn/tetris-discord#9]
Unsure what is the source but it happened exactly once even though the `update_leaderboard` task runs every 5 minutes, but, I think it might be tinydb or python iterating through the inserted data instead of doing it all at once and the timing for these overlapped..
It might as well be nothing important or a one time in ever thing

```py
Traceback (most recent call last):
  File "[...]discord/ext/tasks/__init__.py", line 168, in _loop
    await self.coro(*args, **kwargs)
  File "[...]/bot/exts/tetris/stats.py", line 52, in update_leaderboard
    top = sorted(
  File "[...]/bot/exts/tetris/stats.py", line 53, in <genexpr>
    ({'user_id': i['user_id'], 'score': i['score']} for i in self.db.table(table)),
KeyError: 'user_id'
```

What could be done
- Actually directly use the doc_id
- Maybe somehow try to make tinydb's storage async
- Nothing?

Also probably related to #4

**Comment by dzshn** [comment]
hmm, forget about the "it may be nothing", has happened a few other times and it stops the leaderboard from working

**Comment by dzshn** [comment]
nevermind; turns out the refactor on 10d3a22e21c2f375ec753e16fd2c547b427b0394 wasn't setting user_id for new players...

**Comment by dzshn** [comment]
yup, again. twice already..
